language: csharp

os:
- windows
- linux
- osx

matrix:
  allow_failures:
    - os: windows

mono: none
dotnet: 2.1.502

script:
- dotnet restore
- dotnet build ./GRF/
- dotnet test ./GRF.Tests/

notifications:
    email:
        on_success: never
        on_failure: always